name: Render and Diff

on:
  push:
    # branches:
    #   - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install FreeCAD
        run: |
          sudo add-apt-repository ppa:freecad-maintainers/freecad-daily
          sudo apt-get update
          sudo apt-get install freecad
          sudo pip install freecad-stubs

      - name: Render STL File
        run: |
          pwd
          ls -lah
          # freecadcmd -c "import FreeCAD; import Part; doc = FreeCAD.newDocument(); Part.import('MK2/STL/MK2_bracket-inlet.stl'); doc.recompute(); doc.export('stl_render.png')"
          # freecadcmd -c "import FreeCAD; import Part; doc = FreeCAD.newDocument(); Part.import('path/to/MK2/STL/MK2_bracket-inlet.stl'); doc.recompute(); doc.export('stl_render.png')"
          FreeCADCmd <<EOF
          import FreeCAD
          import FreeCADGui
          import Part
          import Mesh

          # Load the STL file
          mesh = Mesh.Mesh("MK2/STL/MK2_bracket-inlet.stl")

          # Create a new document
          doc = FreeCAD.newDocument("Render")

          # Add the mesh to the document
          part = doc.addObject("Mesh::Mesh", "MyMesh")
          part.Mesh = mesh

          # Set up the view
          FreeCADGui.activeDocument().activeView().viewAxonometric()
          FreeCADGui.activeDocument().activeView().fitAll()

          # Save the view as PNG
          FreeCADGui.activeDocument().activeView().saveImage("output_image.png", 1920, 1080, "White")
          EOF

      - name: Render STEP File
        run: |
          freecadcmd -c "import FreeCAD; import Part; doc = FreeCAD.newDocument(); Part.import('MK2/STEP/MK2_bracket-inlet.stp'); doc.recompute(); doc.saveAs('step_render.png')"

      - name: Compare Images
        run: |
          sudo apt-get install imagemagick
          convert stl_render.png step_render.png -compose Difference -composite diff_result.png

      - name: Upload Diff Image
        uses: actions/upload-artifact@v4
        with:
          name: image-diff
          path: diff_result.png
