name: Render STL Image

on:
  push:
  #   branches:
  #     - main
  # pull_request:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install trimesh matplotlib

    - name: Render STL file
      run: |
        import trimesh
        import matplotlib.pyplot as plt
        from mpl_toolkits.mplot3d import Axes3D

        # Load the STL file
        mesh = trimesh.load('MK2/STEP/MK2_bracket-inlet.stp')

        # Create a 3D plot
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')

        # Extract vertices and faces
        vertices = mesh.vertices
        faces = mesh.faces

        # Plot the mesh
        ax.plot_trisurf(vertices[:, 0], vertices[:, 1], vertices[:, 2], triangles=faces, linewidth=0.2, antialiased=True)

        # Save the figure as an image
        plt.savefig('stl_render.png')


# name: Render and Diff

# on:
#   push:
#     # branches:
#     #   - main

# jobs:
#   render:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Install FreeCAD
#         run: |
#           sudo add-apt-repository ppa:freecad-maintainers/freecad-daily
#           sudo apt-get update
#           sudo apt-get install freecad
#           sudo pip install freecad-stubs

#       - name: Render STL File
#         run: |
#           pwd
#           ls -lah
#           # freecadcmd -c "import FreeCAD; import Part; doc = FreeCAD.newDocument(); Part.import('MK2/STL/MK2_bracket-inlet.stl'); doc.recompute(); doc.export('stl_render.png')"
#           # freecadcmd -c "import FreeCAD; import Part; doc = FreeCAD.newDocument(); Part.import('path/to/MK2/STL/MK2_bracket-inlet.stl'); doc.recompute(); doc.export('stl_render.png')"
#           # freecad .github/scripts/render.py
#           freecadcmd -c "import FreeCAD; import Part; doc = FreeCAD.newDocument(); Part.open('MK2/STL/MK2_bracket-inlet.stl'); doc.recompute(); doc.export('stl_render.png')"


#       - name: Render STEP File
#         run: |
#           freecadcmd -c "import FreeCAD; import Part; doc = FreeCAD.newDocument(); Part.import('MK2/STEP/MK2_bracket-inlet.stp'); doc.recompute(); doc.saveAs('step_render.png')"

#       - name: Compare Images
#         run: |
#           sudo apt-get install imagemagick
#           convert stl_render.png step_render.png -compose Difference -composite diff_result.png

#       - name: Upload Diff Image
#         uses: actions/upload-artifact@v4
#         with:
#           name: image-diff
#           path: diff_result.png
